import Vue from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import vuetify from "./plugins/vuetify";
import BootstrapVue from "bootstrap-vue";
import Notifications from "vue-notification";
import { library } from "@fortawesome/fontawesome-svg-core";
import filters from "./filters";

Vue.use(BootstrapVue);
Vue.use(Notifications);
Vue.use(filters);

import {
  faArrowCircleLeft,
  faArrowAltCircleDown,
  faMapMarkerAlt,
  faCalculator,
  faTimes,
  faClipboardList,
  faMapMarkedAlt,
  faAngleUp,
  faAngleDown,
  faPlusCircle,
  faPrint,
  faUser,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faWarehouse,
  faCog,
  faUsers,
  faChevronDown,
  faSuitcase,
  faTruck,
  faMoneyCheckAlt,
  faLayerGroup,
  faUserAlt,
  faPowerOff,
  faThLarge,
  faSignOutAlt,
  faAlignRight,
  faAlignLeft,
  faBuilding,
  faCheck,
  faLocationArrow,
  faPlug,
  faShapes,
  faCaretRight,
  faExclamationCircle,
  faExclamationTriangle,
  faPlus,
  faSlidersH,
  faTrash,
  faPencilAlt,
  faBan,
  faCircle,
  faUserTag,
  faSpinner,
  faCaretDown,
  faPen,
  faDownload,
  faTruckLoading,
  faTrailer,
  faCloudDownloadAlt,
  faArchway,
  faEdit,
  faFileCsv,
  faFilePdf,
  faPlay,
  faCaretUp,
  faQuestionCircle,
  faMoneyBillWaveAlt,
  faChevronCircleLeft,
  faChevronCircleRight,
  faThumbsUp,
  faExternalLinkAlt,
  faColumns,
  faGripHorizontal,
  faAngleRight,
  faComment,
  faComments,
  faLightbulb,
  faArchive,
  faHandHoldingUsd,
  faCoins,
  faChartLine,
  faRedoAlt,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

Vue.component("font-awesome-icon", FontAwesomeIcon);
library.add(
  faArrowCircleLeft,
  faArrowAltCircleDown,
  faMapMarkerAlt,
  faTimes,
  faCloudDownloadAlt,
  faClipboardList,
  faMapMarkedAlt,
  faAngleUp,
  faCalculator,
  faChevronDown,
  faAngleDown,
  faPlusCircle,
  faPrint,
  faUser,
  faChevronDown,
  faChevronUp,
  faChevronRight,
  faChevronLeft,
  faWarehouse,
  faCog,
  faUsers,
  faSuitcase,
  faTruck,
  faMoneyCheckAlt,
  faLayerGroup,
  faUserAlt,
  faPowerOff,
  faThLarge,
  faSignOutAlt,
  faAlignRight,
  faAlignLeft,
  faBuilding,
  faCheck,
  faLocationArrow,
  faPlug,
  faShapes,
  faCaretRight,
  faExclamationCircle,
  faExclamationTriangle,
  faPlus,
  faSlidersH,
  faTrash,
  faPencilAlt,
  faBan,
  faCircle,
  faUserTag,
  faSpinner,
  faCaretDown,
  faPen,
  faDownload,
  faTruckLoading,
  faTrailer,
  faArchway,
  faEdit,
  faFileCsv,
  faFilePdf,
  faPlay,
  faCaretUp,
  faQuestionCircle,
  faMoneyBillWaveAlt,
  faChevronCircleLeft,
  faChevronCircleRight,
  faThumbsUp,
  faExternalLinkAlt,
  faColumns,
  faGripHorizontal,
  faAngleRight,
  faComment,
  faComments,
  faLightbulb,
  faArchive,
  faHandHoldingUsd,
  faCaretDown,
  faCoins,
  faChartLine,
  faRedoAlt
);

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  vuetify,
  render: (h) => h(App),
}).$mount("#app");
